export default {
  SHOW_DATE_PICKER: 'SHOW_DATE_PICKER',
  CLOSE_DATE_PICKER: 'CLOSE_DATE_PICKER',
  GET_DATE: 'GET_DATE',
  GET_TIME: 'GET_TIME',
  USER_CONFIRM: 'USER_CONFIRM',
  GET_ORDERID: 'GET_ORDERID',
  SET_PARKED: 'SET_PARKED'
};
